package com.example.compoundinggrowth.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

data class Budget (
    var ownerName: String = "",
    var ownerUid: String = "",
    var uuid : String = "", // Unique identifier for transaction
    var category: String = "", // Budget category
    var budgeted: Double = 0.0, // Transaction Amount
    var remaining: Double = 0.0, // Transaction Amount
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
