package com.example.compoundinggrowth.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.io.Serializable
import java.util.Date

data class Transaction (    // Auth information
    var ownerName: String = "",
    var ownerUid: String = "",
    var uuid : String = "", // Unique identifier for transaction
    var name : String = "", // Transaction name
    var amount: Double = 0.0, // Transaction Amount
    var date: Date = Date(), // Transaction Date
    var account: String = "", // Account
    var category: String? = null, // Budget category
    var stockSymbol: String? = null, // For investment tracking
    var stockPriceAtTransaction: Double? = null, // For investment tracking
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
) : Serializable {

    companion object {
        private fun find(fulltext: String, subtext: String): Boolean {
            if (subtext.isEmpty()) return true
            val i = fulltext.indexOf(subtext, ignoreCase = true)
            return i != -1
        }

        val incomeCategories = setOf(
            "income",
            "paycheck",
        )

        val expenseCategories = setOf(
            "shopping",
            "food and drink",
            "housing",
            "auto",
            "entertainment"
        )

    }

    // Given a search string, look for it in the Transaction
    fun searchFor(searchTerm: String): Boolean {
        return find(name, searchTerm)
    }

    override fun equals(other: Any?) : Boolean =
        if (other is Transaction) {
            uuid == other.uuid
        } else {
            false
        }

    override fun hashCode(): Int {
        var result = uuid.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + amount.hashCode()
        result = 31 * result + date.hashCode()
        result = 31 * result + category.hashCode()
        result = 31 * result + (stockSymbol?.hashCode() ?: 0)
        result = 31 * result + (stockPriceAtTransaction?.hashCode() ?: 0)
        return result
    }
}