package com.example.compoundinggrowth.model

import android.icu.util.CurrencyAmount
import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

data class Transaction (    // Auth information
    var ownerName: String = "",
    var ownerUid: String = "",
    var uuid : String = "", // Unique identifier for transaction
    var name : String = "", // Transaction name
    var amount: Double = 0.0, // Transaction Amount
    var date: Date = Date(), // Transaction Date
    var category: String = "", // Budget category
    var stockSymbol: String? = null, // For investment tracking
    var stockPriceAtTransaction: Double? = null, // For investment tracking
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)